ajax_app/config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :students
  root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ajax_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ajax_app/app/models/blog.rb
class Blog < ApplicationRecord
  has_one_attached :image
end

ajax_app/app/models/student.rb
class Student < ApplicationRecord
end

ajax_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ajax_app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def new
    @student = Student.new
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to root_path, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to root_path, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :address, :cource, :age)
    end
end

ajax_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ajax_app/app/helpers/blogs_helper.rb
module BlogsHelper
end

ajax_app/app/helpers/students_helper.rb
module StudentsHelper
end

ajax_app/app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ajax_app/app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

ajax_app/app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

ajax_app/app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

ajax_app/app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @blog.image, class: 'user-img' %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

ajax_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ajax_app/app/views/students/_edit.html.erb
<div class="modal-header">
  <h4 class='text-left modal-title'>
	<h1>Editing Student</h1>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </h4>
</div>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student, remote: true %> |
<%= link_to 'Back', students_path %>

ajax_app/app/views/students/_form.html.erb
<div data-controller = 'student'>
  <%= form_with(model: student, local: true, class: 'form-horizontal x_content' ) do |form| %>
    <% if student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>
        <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>

    <div class="field">
      <%= form.label :cource %>
      <%= form.text_field :cource %>
    </div>

    <div class="field">
      <%= form.label :age %>
      <%= form.number_field :age %>
    </div>

    <div class="actions">
      <%= form.submit remote: true %>
    </div>
  <% end %>
<div>

ajax_app/app/views/students/_new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

ajax_app/app/views/students/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Cource:</strong>
  <%= @student.cource %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<%= link_to 'Edit', edit_student_path(@student), remote: true %> |
<%= link_to 'Back', students_path %>

ajax_app/app/views/students/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'edit', student: @student %>");
$("#modal-window").modal();

ajax_app/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Cource</th>
      <th>Age</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.address %></td>
        <td><%= student.cource %></td>
        <td><%= student.age %></td>
        <td><%= link_to 'Show', student, remote: true %></td>
        <td><%= link_to 'Edit', edit_student_path(student), remote: true %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, remote: true, data: {toggle:  "modal", target: '#modal-window', class: 'btn btn-primary btn-lg'} %>


<div id="modal-window" class="modal fade" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

ajax_app/app/views/students/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'new', student: @student %>");
$("#modal-window").modal();

ajax_app/app/views/students/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'show', student: @student %>");
$("#modal-window").modal();